package com.genealogy.imports.repository;
import com.genealogy.common.persistence.PageResult; import com.genealogy.imports.entity.ImportJobRowEntity; import com.genealogy.imports.repository.mybatis.ImportJobRowPersistenceMapper; import com.genealogy.imports.repository.query.ImportJobRowCount;
import org.springframework.dao.OptimisticLockingFailureException; import org.springframework.data.domain.Page; import org.springframework.data.domain.PageImpl; import org.springframework.data.domain.Pageable; import org.springframework.stereotype.Repository; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Repository @Transactional(readOnly=true) public class ImportJobRowRepository { private final ImportJobRowPersistenceMapper mapper; public ImportJobRowRepository(ImportJobRowPersistenceMapper mapper){this.mapper=mapper;}
 @Transactional public ImportJobRowEntity save(ImportJobRowEntity e){Objects.requireNonNull(e); if(e.getId()==null){if(e.getVersion()==null)e.setVersion(0L); mapper.insert(e);} else {long v=e.getVersion()==null?0:e.getVersion(); if(mapper.updateWithVersion(e)!=1) throw new OptimisticLockingFailureException("Import row version conflict"); e.setVersion(v+1);} return e;} @Transactional public ImportJobRowEntity saveAndFlush(ImportJobRowEntity e){return save(e);}
 @Transactional public List<ImportJobRowEntity> saveAll(Iterable<ImportJobRowEntity> es){if(es==null)return List.of(); List<ImportJobRowEntity> saved=new ArrayList<>(); es.forEach(e->saved.add(save(e))); return saved;} public void flush(){}
 public Optional<ImportJobRowEntity> findById(Long id){return Optional.ofNullable(id==null?null:mapper.selectById(id));} public Optional<ImportJobRowEntity> findByIdAndJobId(Long id,Long j){return Optional.ofNullable(mapper.findByIdAndJobId(id,j));} public Optional<ImportJobRowEntity> findByJobIdAndRowNo(Long j,Integer r){return Optional.ofNullable(mapper.findByJobIdAndRowNo(j,r));} public Optional<ImportJobRowEntity> findByJobIdAndRowNoForUpdate(Long j,Integer r){return Optional.ofNullable(mapper.findByJobIdAndRowNoForUpdate(j,r));}
 public PageResult<ImportJobRowEntity> page(Long j,Collection<String>s,boolean p,int page,int size){return new PageResult<>(mapper.page(j,s,p,(long)Math.max(page,0)*size,size),mapper.count(j,s,p));}
 public List<ImportJobRowEntity> findByJobIdAndRowStatusOrderByRowNoAsc(Long j,String s){return mapper.findByJobAndStatuses(j,List.of(s));} public List<ImportJobRowEntity> findByJobIdAndRowStatusInOrderByRowNoAsc(Long j,Collection<String>s){return mapper.findByJobAndStatuses(j,s);} public Page<ImportJobRowEntity> findByJobIdAndRowStatusInOrderByRowNoAsc(Long j,Collection<String>s,Pageable pageable){if(pageable==null){List<ImportJobRowEntity> rows=findByJobIdAndRowStatusInOrderByRowNoAsc(j,s); return new PageImpl<>(rows);} List<ImportJobRowEntity> rows=mapper.page(j,s,false,pageable.getOffset(),pageable.getPageSize()); return new PageImpl<>(rows,pageable,mapper.count(j,s,false));}
 public List<ImportJobRowEntity> findByJobIdAndRowNoInOrderByRowNoAsc(Long j,Collection<Integer>r){return r==null||r.isEmpty()?List.of():mapper.findByRowNos(j,r);}
 public List<ImportJobRowEntity> findByJobIdAndRowStatusAndPublishedAtIsNullOrderByRowNoAsc(Long j,String s,int limit){return mapper.page(j,List.of(s),true,0,limit);}
 public List<ImportJobRowCount> countByJobIdsAndRowStatus(Collection<Long> j,String s){return j==null||j.isEmpty()?List.of():mapper.countByJobIdsAndStatus(j,s);}
 public long countByJobId(Long j){return mapper.count(j,null,false);} public long countByJobIdAndRowStatus(Long j,String s){return mapper.count(j,List.of(s),false);} public long countByJobIdAndRowStatusIn(Long j,Collection<String>s){return mapper.count(j,s,false);} public long countByJobIdAndRowStatusAndPublishedAtIsNull(Long j,String s){return mapper.count(j,List.of(s),true);}
}
