package com.genealogy.imports.repository;
import com.genealogy.common.persistence.PageResult; import com.genealogy.imports.entity.ImportJobEntity; import com.genealogy.imports.repository.mybatis.ImportJobPersistenceMapper; import com.genealogy.imports.repository.query.ImportJobQueryCriteria;
import org.springframework.stereotype.Repository; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
@Repository @Transactional(readOnly=true) public class ImportJobRepository { private final ImportJobPersistenceMapper mapper; public ImportJobRepository(ImportJobPersistenceMapper mapper){this.mapper=mapper;}
 @Transactional public ImportJobEntity save(ImportJobEntity e){Objects.requireNonNull(e); e.normalizeDescriptor(); LocalDateTime now=LocalDateTime.now(); if(e.getId()==null){if(e.getCreatedAt()==null)e.setCreatedAt(now); e.setUpdatedAt(now); mapper.insert(e);} else {e.setUpdatedAt(now); if(mapper.updateAllById(e)!=1) throw new IllegalStateException("Import job update failed: "+e.getId());} return e;}
 public Optional<ImportJobEntity> findById(Long id){return Optional.ofNullable(id==null?null:mapper.selectById(id));} public List<ImportJobEntity> findAllById(Iterable<Long> ids){List<Long> a=new ArrayList<>(); if(ids!=null)ids.forEach(a::add); return a.isEmpty()?List.of():mapper.findAllByIds(a);}
 public List<ImportJobEntity> findByClanIdOrderByCreatedAtDesc(Long id){return mapper.findByClanId(id);} public Optional<ImportJobEntity> findByIdAndClanId(Long id,Long c){return Optional.ofNullable(mapper.findByIdAndClanId(id,c));} public Optional<ImportJobEntity> findFirstByClanIdAndIdempotencyKeyOrderByCreatedAtDesc(Long c,String k){return Optional.ofNullable(mapper.findFirstByIdempotencyKey(c,k));}
 public Optional<ImportJobEntity> findByIdAndClanIdForUpdate(Long id,Long c){return Optional.ofNullable(mapper.findByIdAndClanIdForUpdate(id,c));} public Optional<ImportJobEntity> findNextExecutableForUpdate(LocalDateTime n){return Optional.ofNullable(mapper.findNextExecutableForUpdate(n));}
 public PageResult<ImportJobEntity> search(ImportJobQueryCriteria c,int page,int size){long offset=(long)Math.max(page,0)*size; return new PageResult<>(mapper.search(c,offset,size),mapper.countSearch(c));}
}
